app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false

  # Whitelist reading from remote URLs
  reading:
    allow:
      - host: raw.githubusercontent.com
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  endpoints:
    '/grafana/api':
      target: http://139.59.77.78:31464/
      changeOrigin: true
      credentials: require
      headers:
        Authorization: Basic ${GRAFANA_AUTH}
    '/argocd/api':
      target: https://139.59.77.78:32447/api/v1/
      changeOrigin: true
      secure: false
      headers:
        Cookie: argocd.token=${ARGOCD_AUTH_TOKEN}

grafana:
  domain: http://139.59.77.78:31464
  unifiedAlerting: true

argocd:
  baseUrl: https://139.59.77.78:32447
  username: admin
  password: ${ARGOCD_PASSWORD}
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: main
          url: https://139.59.77.78:32447
          username: admin
          password: ${ARGOCD_PASSWORD}

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/github/provider#resolvers
            - resolver: usernameMatchingUserEntityName

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]

  providers:
    github:
      providerId:
        organization: 'Shrinet82' # Discover personal repos
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 3 }
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../catalog-info.yaml

    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Portfolio Templates
    - type: file
      target: ../../examples/templates/react-app/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/express-backend/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/flask-api/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/go-service/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/springboot-service/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/aws-s3/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/aws-vpc/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/aws-rds/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/templates/argocd-deploy/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../catalog/backstage-infra.yaml
      rules:
        - allow: [Component]

    - type: file
      target: ../../catalog/resources/*.yaml
      rules:
        - allow: [Resource]

    - type: file
      target: ../../catalog/services/*.yaml
      rules:
        - allow: [Component]

    - type: file
      target: ../../catalog/systems/*.yaml
      rules:
        - allow: [System]

    - type: file
      target: ../../catalog/domains/*.yaml
      rules:
        - allow: [Domain]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    - type: file
      target: ../../examples/user-shrinet82.yaml
      rules:
        - allow: [User]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

    # Sample Component from Video Tutorial
    - type: file
      target: ../../examples/my-library.yaml

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${K8S_URL}
          name: digitalocean-cluster
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          serviceAccountToken: ${K8S_TOKEN}
          caData: ${K8S_CA_DATA}

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true
